### ISSUE TITLE
Encoding error of column 'sales_to_stop_place_name'

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-entur#6]
# Problem / Motivation

There is an encoding problem when importing stop place names from entur sales (cleos) to the column `sales_to_stop_place_name`:

![Image](https://github.com/TromsFylkestrafikk/ragnarok-entur/assets/47245416/6547ae5b-1e86-4bc1-bb87-e526f9282267)

# Suggested resolution

The importer is using CsvToTable with mapping between csv column and DB columns. There might be need to perform some `iconv()` substitution here, if there are no other way to properly set up source/destination encoding

# Definition of done

- [ ] Imported stop place names have proper utf encoding.

**Comment by jbtfk** [comment]
From command line in linux shell:
```
file S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv
S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv: Unicode text, UTF-8 text, with very long lines (1072), with CRLF, LF line terminators
```

From log when fetching data, checking with mb_detect_encoding()
```
[2024-06-17 13:47:33] local.DEBUG: [EnTur CLEOS]: FILE: S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv  
[2024-06-17 13:47:33] local.DEBUG: [EnTur CLEOS]: ENCODING: UTF-8 
```

**Comment by tfk-kaare** [comment]
I see the `CsvToTable::setupCsvReader()` has a lot of encoding stuff. Strange though, that the raw file in utf-8 is encoded wrong. CsvToTable is setup to accept utf-8 as the default encoding :-(

**Comment by jbtfk** [comment]
Opened in in hex-editor, Å is 0xC3 0xA5 as expected from UTF 8

**Comment by jbtfk** [comment]
local database default charset: utf8mb4, table charset: utf8mb4

Example output from simple script run locally:

```
Encoding: UTF-8, string: TromsÃ¸ lufthavn
Encoding: ASCII, string: Maukstadmoen Leir
Encoding: ASCII, string: 
Encoding: UTF-8, string: Harstad hurtigbÃ¥tkai
Encoding: ASCII, string: 
Encoding: ASCII, string: 
Encoding: ASCII, string: Bankgata
Encoding: ASCII, string: 
Encoding: UTF-8, string: TromsÃ¸ Prostneset
Encoding: ASCII, string: Universitetssykehuset Nord-Norge
```

output checked in hex-editor, still UTF-8 byte codes

**Comment by jbtfk** [comment]
There is no BOM in the datastream. Tried adding BOM manually, and seems to fix the issue locally

**Comment by jbtfk** [comment]
Adding BOM as is done in first example below seems to fix it locally

```
// chr(239) . chr(187) . chr(191) . $fetchedData

file S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv 
S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv: Unicode text, UTF-8 (with BOM) text, with very long lines (1072), with CRLF, LF line terminators

// VS

file S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv
S-1_CSV2Troms_Fylkeskommune_Samferdsel_2024-06-17_2024061771534_v24.csv: Unicode text, UTF-8 text, with very long lines (1072), with CRLF, LF line terminators
```
